"""empty message

Revision ID: 335330889598
Revises: b03e912d7de7
Create Date: 2023-02-18 19:13:53.220872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335330889598'
down_revision = 'b03e912d7de7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replylist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boardlist.id'], name=op.f('fk_replylist_board_id_boardlist')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_replylist'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replylist')
    # ### end Alembic commands ###
