"""empty message

Revision ID: fe80f81ef69f
Revises: 5cf4ad4ad7cf
Create Date: 2023-02-26 22:35:21.200085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe80f81ef69f'
down_revision = '5cf4ad4ad7cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.drop_column('board', 'modify_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('modify_date', mysql.DATETIME(), nullable=True))
    op.drop_column('board', 'update_date')
    # ### end Alembic commands ###
